name: jusicool_ios
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  tes:
    git:
      url: https://github.com/Jusicool-Ver-2-0/Jusicool-iOS-DesignSystem.git
      ref: main
  flutter_svg: ^2.0.17
  flutter_native_splash: ^2.4.6
  email_validator: ^3.0.0

flutter_native_splash:
  color: "#FFFFFF" 
  image: assets/images/JUSICOOL.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true

  assets:
    - assets/images/